services:

  # --- MariaDB ---
  db:
    image: mariadb:latest
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=3b9d778c65a3f08eb03a66e30d37b5feeda500f26b7a1739e3e4fb4d7e25c5d8
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=f7d2a7917bb1a0a7f7bdcb642883359e17dcd0cad794a54cd733dd1761f1db97
    volumes:
      - /mnt/ext4_data/nextcloud/db:/var/lib/mysql

  # --- Nextcloud App ---
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: unless-stopped
    user: 1000:1000
    depends_on:
      - db
    environment:
      - PHP_MEMORY_LIMIT=1024M
      - MYSQL_PASSWORD=f7d2a7917bb1a0a7f7bdcb642883359e17dcd0cad794a54cd733dd1761f1db97
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.ngeorgiev.com
    volumes:
      - /mnt/ext4_data/nextcloud/html:/var/www/html
      - /mnt/ext4_data/nextcloud/data:/var/www/html/data

  # --- Nextcloud Cron ---
  cron:
    build: ./nextcloud-cron
    image: nextcloud-cron:latest
    container_name: nextcloud-cron
    restart: unless-stopped
    environment:
      - PHP_MEMORY_LIMIT=1024M
    depends_on:
      - db
      - app
    volumes:
      - /mnt/ext4_data/nextcloud/html:/var/www/html
      - /mnt/ext4_data/nextcloud/data:/var/www/html/data

  # --- Nginx Reverse Proxy ---
  nginx:
    image: nginx:latest
    container_name: nextcloud-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app

  # --- Certbot for TLS certificates ---
  certbot:
    image: certbot/certbot
    container_name: nextcloud-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet;
      sleep 12h & wait $${!}; done"
